version: "3.5"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: td-cloud
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
